on: push
name: CI
jobs:
  build:
    name: Build server executables
    strategy:
      matrix:
        platform:
          - { os: ubuntu-latest, artifact: "x86_64-linux", exe_ext: "" }
          - { os: windows-latest, artifact: "x86_64-windows", exe_ext: ".exe" }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p remote-runner-server
      - uses: actions/upload-artifact@v2
        with:
          name: remote-runner-server.${{ matrix.platform.artifact }}${{ matrix.platform.exe_ext }}
          path: target/release/remote-runner-server${{ matrix.platform.exe_ext }}
